replicaCount: 3

image:
    repository: ghcr.io/techgardencode/www
    pullPolicy: IfNotPresent
    tag: "b786207a0093938e89a5d321d2f626b463efce94"
    imagePullSecrets:
        - name: dockerconfigjson-github-com

service:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
    enabled: true
    className: nginx
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
        - host: techgarden.gg
          paths:
              - path: /
                pathType: Prefix
        - host: www.techgarden.gg
          paths:
              - path: /
                pathType: Prefix
    tls:
        enabled: true
        secretName: www-techgarden-gg-tls
